### PR TITLE
databases/week1

### PR DESCRIPTION
**Pull request by islam-fawzy25**

### CODE REVIEW

**Comment by Elia-Git** [comment]
Your homework file is empty. Would you please push your homework so I can review it?

**Comment by islam-fawzy25** [comment]
> Your homework file is empty. Would you please push work so I can review it?

Hi Elia 
sorry for this mistake now i make sure its not empty file .
but i see there is commit from last branch on this branch it will make problems , do you think ?

**Review by Elia-Git — COMMENTED** [review]
Good job Islam. Let me see your changes and can ship it out.

**Review by Elia-Git — COMMENTED** [review]
Good job Islam. 
Small things to fix. 
Be aware of using " * " everywhere. Use it if you really need it (where it make sense). Otherwise, it could disturb your work. You can a specific selection for key columns instead.

**Comment by islam-fawzy25** [comment]
> Good job Islam.
> Small things to fix.
> Be aware of using " * " everywhere. Use it if you really need it (where it make sense). Otherwise, it could disturb your work. You can a specific selection for key columns instead.

Thanks Elia for your helping , i will keep that in mind

**Pull request merged**
