### PR TITLE
 conflict solved

### PR DESCRIPTION
**Pull request by islam-fawzy25**

### CODE REVIEW

**Comment by KavyaReddy732** [comment]
here are some modifications
1.after pulling the latest changes on GitHub you need to merge the changes with feature/veggies(command: git merge <branchname>)
2.then commit and push the branch and make a PR.

**Comment by islam-fawzy25** [comment]
Hi Kavya, 
thanks for helping 
but i confused , i checked my file there are no lines 1 and 2 on PR but I can see them locally ---- check screen shoot
I tried to commit and push again but still can not see them 
I don't know why 
should you help me ?
git week2

**Comment by KavyaReddy732** [comment]
Try git merge git/week2 on this branch.

**Comment by islam-fawzy25** [comment]
Yes , i tried as you can see here 
git issue

**Pull request merged**
